# Generated by Django 5.2.7 on 2025-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aparato', models.CharField(max_length=50, verbose_name='Tipo de Aparato')),
                ('marca_modelo', models.CharField(max_length=100, verbose_name='Marca y Modelo')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_falla', models.TextField(verbose_name='Falla Reportada')),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Equipo Recibido'), ('DIAGNOSTICO', 'En Diagnóstico'), ('PRES_ESPERA', 'Presupuesto Esperando Aprobación'), ('REPARACION', 'En Reparación'), ('LISTO', 'Listo para Entrega'), ('ENTREGADO', 'Equipo Entregado'), ('FALLA', 'Falla No Reparable')], default='RECIBIDO', max_length=20, verbose_name='Estado Actual')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
