# Generated by Django 5.2.8 on 2025-11-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('cantidad_total_aparatos', models.IntegerField(default=0, verbose_name='Total de Aparatos')),
                ('detalles_servicios', models.TextField(help_text='Lista de aparatos seleccionados con sus cantidades.', verbose_name='Detalles de Aparatos')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Proceso'), ('F', 'Finalizado'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Estado de Solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.usuario', verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio',
                'verbose_name_plural': 'Solicitudes de Servicio',
            },
        ),
        migrations.DeleteModel(
            name='Reparacion',
        ),
    ]
