# Generated by Django 5.2.8 on 2025-11-23 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_servicio_delete_reparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('num_exterior', models.CharField(max_length=20, verbose_name='Número Exterior')),
                ('referencias', models.TextField(blank=True, help_text='Color de casa, calle o negocio cercano.', null=True)),
                ('comentario', models.TextField(verbose_name='Descripción del Problema')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_domicilio', to='local.usuario', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Consulta a Domicilio',
                'verbose_name_plural': 'Consultas a Domicilio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
