# Generated by Django 5.2.8 on 2025-11-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_domicilio', to='local.usuario', verbose_name='Cliente'),
        ),
    ]
