# Generated by Django 5.2.8 on 2025-11-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_alter_consulta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='codigo_postal',
            field=models.CharField(max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='colonia',
            field=models.CharField(max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='referencias',
            field=models.TextField(blank=True, help_text='Color de casa, calle o negocio cercano.', null=True, verbose_name='Referencias'),
        ),
    ]
