# Generated by Django 5.2.8 on 2025-11-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_alter_consulta_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Consulta a Domicilio', 'verbose_name_plural': 'Consultas a Domicilio'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigo_postal',
            field=models.CharField(max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='colonia',
            field=models.CharField(max_length=100, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='comentario',
            field=models.CharField(max_length=20, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='num_exterior',
            field=models.CharField(max_length=20, verbose_name='Número Exterior'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='referencias',
            field=models.TextField(blank=True, help_text='Color de casa, calle o negocio cercano.', null=True, verbose_name='Referencias'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_domicilio', to='local.usuario', verbose_name='Cliente'),
        ),
    ]
