# Generated by Django 5.2.8 on 2025-11-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0010_alter_consulta_options_alter_consulta_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
