# Generated by Django 5.2.8 on 2025-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0012_solicitud_delete_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='comentario',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
