# Generated by Django 5.2.8 on 2025-11-23 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0013_alter_consulta_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparato', models.CharField(choices=[('TV', 'Televisor LED/OLED'), ('HT', 'Home Theater'), ('BA', 'Bocinas / Altavoces'), ('AMP', 'Amplificadores'), ('EQS', 'Equipo de Estéreo'), ('MW', 'Microondas'), ('HRN', 'Hornos'), ('LIC', 'Licuadoras'), ('BAT', 'Batidoras'), ('TST', 'Tostadoras'), ('VT', 'Ventiladores'), ('PR', 'Planchas de Ropa'), ('SD', 'Secadora de Pelo'), ('PC', 'Plancha de Cabello'), ('RC', 'Rizador de Cabello')], max_length=50, verbose_name='Aparato Solicitado')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado del Servicio')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Servicio Solicitado',
                'verbose_name_plural': 'Servicios Solicitados',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
