# Generated by Django 5.2.8 on 2025-11-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0014_serviciosolicitado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciosolicitado',
            options={},
        ),
        migrations.RemoveField(
            model_name='serviciosolicitado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='serviciosolicitado',
            name='user',
        ),
        migrations.AddField(
            model_name='serviciosolicitado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.usuario'),
        ),
        migrations.AlterField(
            model_name='serviciosolicitado',
            name='aparato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviciosolicitado',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviciosolicitado',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
