# Generated by Django 5.2.8 on 2025-11-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0018_remove_usuario_username_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
